### ISSUE TITLE
Cambio query lluvia

### ISSUE THREAD

**Issue by LucasCapozzelli** [SPAUTN/SPA-Backend#15]
Se modifica la query actual que trae las precipitaciones acumuladas por día (utilizando la fecha), por la consulta que se ve a continuación donde trae las precipitaciones acumuladas en las últimas 24hs debido a que no se va a regar a las 00:00 hs.

```SQL
SELECT SUM(pluviometer) as precipitacion_acumulada
FROM spa.weatherstation
WHERE timestamp >= NOW() - interval '24 hours';

```

**Comment by julian87nicolas** [comment]
Hice esta query, cuando tengamos mas datos sin tantos IRR podemos probarla mejor, pero por el momento creo que va bien

```sql
SELECT sum(pluviometer) AS cumulative_rain
    FROM spa.weatherstation
    WHERE DATE_TRUNC('minute',timestamp) >= (
        SELECT DATE_TRUNC('minute',timestamp) AS truncated_date
        FROM spa.wetweights
        ORDER BY timestamp DESC
        LIMIT 1);
```

De la subquery 
```sql
SELECT DATE_TRUNC('minute',timestamp) AS truncated_date
        FROM spa.wetweights
        ORDER BY timestamp DESC
        LIMIT 1
```
Se obtiene la fecha truncada hasta el valor de los minutos del ultimo dato en la tabla de wetweights, el cual se obtiene justo despues de regar. Esta fecha se usa para la condición en la query, donde se suman todos los valores de `pluviometer` cuya fecha sea mayor a la obtenida anteriormente.
